version: '3.7'

services:

  learn:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: learn
    restart: unless-stopped
    ports:
      - "8000"

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app/frontend/:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - learn:learn
    environment:
      - VIRTUAL_HOST=en.db.rv.ua
      - VIRTUAL_PORT=80